apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: weather-api
  description: A .NET API providing weather forecasts
  owner: guests
  tags:
    - weather
    - api
spec:
  type: service
  lifecycle: production
  owner: guests
  providesApis:
    - weather-api
links:
    - url: 'https://github.com/NimmyDBS/WebApiNew'
      title: 'GitHub Repository'   
    - url: 'https://sonarqube.ey.com/dashboard?id=eyse_application_security'
      title: 'SonarQube Dashboard'
